### ISSUE TITLE
Check only tests if login node is online or not, not if the share is available.

### ISSUE THREAD

**Issue by jkwmoore** [Carldkennedy/hpc_workflow_recipes#5]
https://github.com/Carldkennedy/hpc_workflow_recipes/blob/1a3a976043e555912c5380972d7ec0b1a3c22824/transfer-files#L47-L63

At present, this script checks if a login node is available to login to via SSH but it doesn't check if the shared area is available on the node.

Ideally we would check the node and the share is both available.

**Comment by Carldkennedy** [comment]
Resolved by #6
